application: gcs-blobstore
version: 1a
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: blob_upload.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest